# Generated by Django 5.2.6 on 2025-12-26 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('userpic', models.ImageField(blank=True, null=True, upload_to='donor/')),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationname', models.CharField(max_length=200, null=True)),
                ('collectionloc', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('donationitem', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('donationpic', models.ImageField(blank=True, null=True, upload_to='donation/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('donationdate', models.DateField(null=True)),
                ('adminremarks', models.TextField(max_length=500, null=True)),
                ('volunteerremark', models.TextField(max_length=500, null=True)),
                ('updationdate', models.DateTimeField(null=True)),
                ('donationarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donationarea')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverypic', models.FileField(null=True, upload_to='')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('userpic', models.ImageField(blank=True, null=True, upload_to='volunteer/')),
                ('idpic', models.ImageField(blank=True, null=True, upload_to='volunteer/')),
                ('aboutme', models.TextField(max_length=1000, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('adminremarks', models.TextField(max_length=500, null=True)),
                ('updationdate', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='Volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
    ]
