# Generated by Django 5.2.6 on 2025-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
